### PR TITLE
Adding Shipment Invoice & Refund Report to Prefix & Type Lists

### PR DESCRIPTION
**Pull request by Justintime50**
The new shipment invoice report prefix needed to be added to the list which I've done so here.

### CODE REVIEW

**Comment by Justintime50** [comment]
Hard to see since I had to indent everything once but I added the following the the types array too:

```php
'RefundReport'          => '\EasyPost\Report',
'ShipmentInvoiceReport' => '\EasyPost\Report',
```

**Comment by att14** [comment]
We'll need to cut a new version as well. @Justintime50 do you want to follow the instructions in https://github.com/EasyPost/easypost-php#releasing?

**Comment by Justintime50** [comment]
@att14 I can definitely do that once this is merged, or I can put up a PR now for a version bump, would need to rebase once this is merged right?

**Comment by att14** [comment]
Yup, go for it!

**Pull request merged**
