### PR TITLE
Docblocks

### PR DESCRIPTION
**Pull request by victoryftw**

### CODE REVIEW

**Comment by browner12** [comment]
glad to help! and thanks for merging, just an FYI, you mistyped my name.

also, when did version 3 come out? is it the current stable version? because if so we should update the readme again to reference that version.

**Comment by victoryftw** [comment]
Thanks for letting me know about the misspelling! I corrected it now.

I also bumped the version in the readme again to reflect that we are now on version 3.

**Comment by browner12** [comment]
according to the changelog, there were no breaking changes. why did you guys bump to v3 instead of a minor or a patch?

**Comment by victoryftw** [comment]
That was originally our plan; however, we realized that the change could in fact be a breaking change if any of our users relied on the old (incorrect) behavior. Since there was a value being returned in the ID field in those cases, just not the correct value, we took the safe approach and made a major version bump just in case anyone was keying off that field.

**Comment by browner12** [comment]
awesome, thanks for the replies

**Pull request merged**
