### PR TITLE
Version bump - 3.5.0

### PR DESCRIPTION
**Pull request by Justintime50**
Bumping version to 3.5.0 with all the changes made from two weeks ago.

### CODE REVIEW

**Comment by Justintime50** [comment]
@Roguelazer how would you like to handle this PR? We had a bunch of changes merged to master some months ago that never had a new version cut.

**Comment by Roguelazer** [comment]
Why don't you give it a rebase on master and I'll look into finding our composer credentials.

**Comment by Justintime50** [comment]
Rebased. 

If we have it setup correct, we should just be able to cut a new version on GitHub and it'll push it to Packagist for us (as long as someone at the org has authorized it to do so).

**Review by Roguelazer — APPROVED** [review]

**Comment by Justintime50** [comment]
Merging this as it's approved. Packagist should automatically release a new version assuming it's still authenticated via someones account.

**Pull request merged**
